### PR TITLE
fix: use IMutableContext when updating context

### LINKED ISSUE #26: TypeScript: useUnleashContext returns a function that expects appName
### Describe the bug

From the example of updating the context dynamically e.g. after knowing the user id/properties:

```
<script lang="ts">
	import { useUnleashContext, useFlag } from '@unleash/proxy-client-svelte';

	export let userId;

	const toggle = useFlag('my-toggle');
	const updateContext = useUnleashContext();

	$: {
		// context is updated with userId
		updateContext({ userId });
	}

	// OR if you need to perform an action right after new context is applied
	$: {
		async function run() {
			// Can wait for the new flags to pull in from the different context
			await updateContext({ userId });
			console.log('new flags loaded for', userId);
		}
		run();
	}
</script>
```

TypeScript complaints with: Property 'appName' is missing in type '{ userId: string; properties: { x: string; }; }' but required in type 'IStaticContext'.

If we add that, then we get a warning on console: 
> appName and environment are static. They can't be updated with updateContext.

Which makes sense.

I believe this is because `updateContext` expects an `IContext` in https://github.com/Unleash/unleash-svelte-sdk/blob/main/src/lib/context.ts#L10C27-L10C35.

I think this should be `IMutableContext`.

### Steps to reproduce the bug

_No response_

### Expected behavior

_No response_

### Logs, error output, etc.

```bash

```

### Screenshots

_No response_

### Additional context

_No response_

### Unleash version

_No response_

### Subscription type

None

### Hosting type

None

### SDK information (language and version)

_No response_

### PR DESCRIPTION
**Pull request by mdanilakis**
## About the changes

Closes #26

### CODE REVIEW

File: src/lib/index.ts [hunk 1]
```diff
@@ -1,6 +1,5 @@
 export type {
 	IConfig,
-	IContext,
 	IMutableContext,
```
Comment (nunogois) [inline src/lib/index.ts]: I believe we should keep exporting this. E.g. [React SDK](https://github.com/Unleash/unleash-react-sdk/blob/main/src/index.ts#L5)
```suggestion
	IContext,
	IMutableContext,
```

**Review by nunogois — CHANGES_REQUESTED** [review]
Hi @mdanilakis, thank you for your contribution!

This looks great, but I think we should continue exporting `IContext` for our SDK consumers. This will help maintain consistency with the React SDK.

**Review by nunogois — APPROVED** [review]
Looks great!

Thank you again for your contribution.
